name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: "master"
  workflow_dispatch:
jobs:

# The job below generates the images displayed on lowlighter/lowlighter
# You can reuse these steps if you want to have a profile page similar to mine.
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: withshubh/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          config_timezone: Asia/Colombo
          config_order: base.header, isocalendar, base.repositories
          config_padding: 10%
          use_prebuilt_image: master 
          
      - name: Personal metrics (additional)
        uses: withshubh/metrics@latest
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          config_timezone: Europe/Paris
          config_order: languages, pagespeed, habits, stargazers, stars
          use_prebuilt_image: master
     
      # Note the job below use a bot token with "public_repo" scope
      - name: Personal projects
        uses: withshubh/metrics@latest
        with:
          filename: metrics.projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: lowlighter
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: lowlighter/metrics/projects/1
          plugin_projects_limit: 0
          config_timezone: Asia/Colombo

      # Google PageSpeed insight audits, with an additional screenshot of your website
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
#      - name: PageSpeed plugin (screenshot)
#        uses: withshubh/metrics@latest
#        with:
#          filename: metrics.plugin.pagespeed.screenshot.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          committer_token: ${{ secrets.GITHUB_TOKEN }}
#          base: ""
#          plugin_pagespeed: yes
#          plugin_pagespeed_screenshot: yes
#          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
#          plugins_errors_fatal: yes
#          config_timezone: Asia/Colombo
#          use_prebuilt_image: master
      - name: Pagespeed plugin (new)
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }} 
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: no
          plugin_pagespeed_url: .user.website  

      # Display recently played music
      # Note that :
      # - "plugin_music_mode", "plugin_music_provider" and "plugin_music_token" are all required
      - name: Music plugin (recent)
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.music.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display coding habits and recent activity
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display most used languages
      # You can ignore some languages and skip some repositories if you want
      - name: Languages plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display ratio of open/closed/merged issues and pull requests 
      - name: Follow-up plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display number of line changed
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      - name: Lines plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display number of repositories views
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      # - A "repo" scope is required
      - name: Traffic plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_traffic: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display recent posts
      # Note that : 
      # - "plugin_posts_source" is required
      # - With "dev.to" as source, your GitHub username is directly used
      - name: Posts plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display isometric calendar (180 days)
      - name: Isocalendar plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display gists metrics
      - name: Gists plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display starred topics (as icons)
      # Note that : 
      # - Only topics with an icon will be displayed (most of majors topics have one anyway)
      - name: Topics plugin (mastered)
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display your latest tweets
      # Don't forget to update your GitHub profile with your twitter username
      # Note that : 
      # - You must provide a "plugin_tweets_token"
      - name: Tweets plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.tweets.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master
          
      # Display your stargazers evolutions
#      - name: Stargazers plugin
#        uses: withshubh/metrics@latest
#        with:
#          filename: metrics.plugin.stargazers.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          committer_token: ${{ secrets.GITHUB_TOKEN }}
#          base: ""
#          plugin_stargazers: yes
#          plugins_errors_fatal: yes
#          config_timezone: Asia/Colombo
#          use_prebuilt_image: master
          
      # Display your latest starred repositories
      - name: Stars plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master
          
      # Display recent activity metrics
      - name: Activity plugin
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 4
          plugin_activity_days: 0
          plugin_activity_filter: push, issue, pr, release
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          config_padding: 10%
          use_prebuilt_image: master

      # This is used to illustrate special features with the use of "debug_flags"
      # - "--cakeday" will act as if it's your account birthday
      # - "--hireable" will act as if "Available for hire" is enabled on your account
      # - "--halloween" will act as if it was halloween, changing the colors of contributions calendar and isocalendar
      - name: Header (additional features)
        uses: withshubh/metrics@latest
        with:
          filename: metrics.header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header"
          debug_flags: --cakeday --hireable --halloween
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # This is used to illustrate plugin errors : 
      # The "METRICS_TOKEN" does not contains the "public_repo" scope, which is required for "plugin_projects"
      # It will display an "Insufficient token rights" error
      - name: Plugin error example
        uses: withshubh/metrics@latest
        with:
          filename: metrics.plugin.error.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: no
          config_timezone: Asia/Colombo
          use_prebuilt_image: master
          
          

