name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push:
    branches: "master"
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal Metrics
      # See action.yml for all options
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories, activity, community, metadata"
          plugin_lines: yes
          plugin_isocalendar: yes
          config_timezone: Asia/Colombo
          config_order: base.header, isocalendar, base.repositories
          config_padding: 10%
          use_prebuilt_image: master 
          
      - name: Personal metrics (additional)
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_languages: yes
#          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
#          plugin_languages_skipped: lowlighter
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          config_timezone: Asia/Colombo
          config_order: languages, pagespeed, habits, stargazers, stars
          use_prebuilt_image: master
     
      # Note the job below use a bot token with "public_repo" scope
#      - name: Personal projects
#        uses: lowlighter/metrics@master
#        with:
#          filename: metrics.projects.svg
#          token: ${{ secrets.METRICS_BOT_TOKEN }}
#          committer_token: ${{ secrets.GITHUB_TOKEN }}
#          user: withshubh
#          base: ""
#          plugin_projects: yes
#          plugin_projects_repositories: lowlighter/metrics/projects/1
#          plugin_projects_limit: 0
#          config_timezone: Asia/Colombo

# The job below generates the examples displayed on lowlighter/metrics
# You can use these steps to render plugins as standalone or to understand how each of them works
# Note that : 
# - "plugins_errors_fatal" is set to "yes" so it'll make the workflow fail in case of errors, but you can set it to "no"
# - You can use the "debug" to print additional logs in your workflow (be sure to put all sensitives informations in your secrets before)
# 
# ⚠️ Following jobs uses @master branch, which is unstable but also contains unreleased features
# ⚠️ Don't use "use_prebuilt_image" option on forks, because you'll end up using official images from lowlighter/metrics
  github-metrics:
    needs: [github-metrics-personal]
    runs-on: ubuntu-latest
    if: "github.repository == 'withshubh/withshubh'"
    steps:

      # Classic template with header and repositories sections
      - name: Classic template
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories, activity, community,metadata"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Google PageSpeed insight audits
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin
        with:
          filename: metrics.plugin.pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Google PageSpeed insight audits, with additional performance metrics displayed
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin (detailed)
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Google PageSpeed insight audits, with an additional screenshot of your website
      # Don't forget to update your GitHub profile with your website
      # Token is optional but advised
      - name: PageSpeed plugin (screenshot)
        with:
          filename: metrics.plugin.pagespeed.screenshot.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display random tracks from the given embed playlist
      # Note that :  
      # - "plugin_music_mode" and "plugin_music_provider" are both optional (they're deduced from "plugin_music_playlist")
      # - "plugin_music_token" is not needed as it uses pupeeter to retrieve tracks
#      - name: Music plugin (playlist)
#        uses: lowlighter/metrics@master
#        with:
#          filename: metrics.plugin.music.playlist.svg
#          token: ${{ secrets.METRICS_TOKEN }}
#          committer_token: ${{ secrets.GITHUB_TOKEN }}
#          base: ""
#          plugin_music: yes
#          plugin_music_playlist: ${{ secrets.MUSIC_PLAYLIST }}
#          plugin_music_limit: 2
#          plugins_errors_fatal: yes
#          config_timezone: Asia/Colombo
#          use_prebuilt_image: master

      # Display recently played music
      # Note that :
      # - "plugin_music_mode", "plugin_music_provider" and "plugin_music_token" are all required
      - name: Music plugin (recent)
        with:
          filename: metrics.plugin.music.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display coding habits and recent activity
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin
        with:
          filename: metrics.plugin.habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display coding habits and recent activity (only facts section)
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin (facts)
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display coding habits and recent activity (only charts section)
      # Don't forget to setup timezone for accurate metrics
      - name: Habits plugin (charts)
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display most used languages
      # You can ignore some languages and skip some repositories if you want
      - name: Languages plugin
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
#          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
#          plugin_languages_skipped: lowlighter
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display ratio of open/closed/merged issues and pull requests 
      - name: Follow-up plugin
        with:
          filename: metrics.plugin.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_followup: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display number of line changed
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      - name: Lines plugin
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_lines: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display number of repositories views
      # Note that :
      # - This is part of "repositories" section, so you need to enable it
      # - A "repo" scope is required
      - name: Traffic plugin
        with:
          filename: metrics.plugin.traffic.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "repositories"
          plugin_traffic: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display recent posts
      # Note that : 
      # - "plugin_posts_source" is required
      # - With "dev.to" as source, your GitHub username is directly used
      - name: Posts plugin
        with:
          filename: metrics.plugin.posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display isometric calendar (180 days)
      - name: Isocalendar plugin
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display gists metrics
      - name: Gists plugin
        with:
          filename: metrics.plugin.gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_gists: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display starred topics (as labels)
      - name: Topics plugin
        with:
          filename: metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 12
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display starred topics (as icons)
      # Note that : 
      # - Only topics with an icon will be displayed (most of majors topics have one anyway)
      - name: Topics plugin (mastered)
        with:
          filename: metrics.plugin.topics.mastered.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # Display active projects
      # Note that : 
      # - As projects requires "public_repo" scope, you can use a bot account instead and use the "user" option instead
      # - It uses user projects by default (those which are on your profile)
      # - You can use repositories projects by providing a list of comma-separated endpoints
      # - You can set "plugin_projects_limit" to 0 to display only "plugin_projects_repositories"
      # - You'll need to enable "Track project progress" in your projects to display a progress bar
 #     - name: Projects plugin
 #       uses: lowlighter/metrics@master
 #       with:
 #         filename: metrics.plugin.projects.svg
 #         token: ${{ secrets.METRICS_BOT_TOKEN }}
 #         committer_token: ${{ secrets.GITHUB_TOKEN }}
 #         base: ""
 #         plugin_projects: yes
 #         plugin_projects_repositories: lowlighter/metrics/projects/1
 #         plugins_errors_fatal: yes
 #         config_timezone: Asia/Colombo
 #         use_prebuilt_image: master

      # Display your latest tweets
      # Don't forget to update your GitHub profile with your twitter username
      # Note that : 
      # - You must provide a "plugin_tweets_token"
      - name: Tweets plugin
        with:
          filename: metrics.plugin.tweets.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master
          
      # Display your stargazers evolutions
      - name: Stargazers plugin
        with:
          filename: metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master
          
      # Display your latest starred repositories
      - name: Stars plugin
        with:
          filename: metrics.plugin.stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 2
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master
          
      # Display recent activity metrics
      - name: Activity plugin
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 4
          plugin_activity_days: 0
          plugin_activity_filter: push, issue, pr, release
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          config_padding: 10%
          use_prebuilt_image: master

      # This is used to illustrate special features with the use of "debug_flags"
      # - "--cakeday" will act as if it's your account birthday
      # - "--hireable" will act as if "Available for hire" is enabled on your account
      # - "--halloween" will act as if it was halloween, changing the colors of contributions calendar and isocalendar
      - name: Header (additional features)
        with:
          filename: metrics.header.svg
          token: ${{ secrets.METRICS_BOT_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header"
          debug_flags: --cakeday --hireable --halloween
          plugins_errors_fatal: yes
          config_timezone: Asia/Colombo
          use_prebuilt_image: master

      # This is used to illustrate plugin errors : 
      # The "METRICS_TOKEN" does not contains the "public_repo" scope, which is required for "plugin_projects"
      # It will display an "Insufficient token rights" error
      - name: Plugin error example
        with:
          filename: metrics.plugin.error.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: no
          config_timezone: Asia/Colombo
          use_prebuilt_image: master
